# 服务器设置
server :
  port: 8081
  tomcat:
    uri-encoding: utf-8
# 数据库设置
spring:
  application:
    name: gift-giving
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gift?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: Wan152280
    initialSize: 5
    minIdle: 5
    maxActive: 100000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

logging:
  level:
    org:
      springframework: WARN
      spring:
        springboot:
          dao: WARN
    java:
      sql: WARN
    com:
      apache:
        ibatis: WARN
      sofn:
        giftgiving:
          mapper: WARN

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sofn.giftgiving



